insert into Foods_CN(Food_ID,Food_Name,Description) values("à blanc","一个白","法国术语,意思是''白人''和识别的食物,通常是肉,不晒黑在做饭。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à la","在","法国成语意思是''在''的方式(或风格);完整的短语是烹饪,de la模式。这个短语指定样式的准备或特定的装饰。,例如,将意味着''勃艮第的准备。''");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à la carte","信用卡","一个菜单项来表示每个项目单独定价。参见客饭,客饭。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à la diable","马虎地","见鬼酱");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à la king","在金","一盘美味的食品(通常是鸡或火鸡)在一个丰富的奶油汁含有蘑菇,有时pimientos、青椒和雪利酒。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à la mode","摩登","法国''的方式(或模式)[的],''他指的是准备一个菜的风格。这个词已经被美国化也意味着派加上冰淇淋。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("a labarigoule","一个labarigoule","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("à point","一个点","1。法国术语用于食物煮熟煮熟度的完美点。2。指肉,意味着牛排煮罕见。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("abalone","鲍鱼","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("abbacchio","abbacchio","意大利很年轻的羔羊。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Abbaye de Belloc (Bellocq)","修道院的Belloc先生(贝略克)","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("abby","艾比","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aboyeur","aboyeur","旅系统");
insert into Foods_CN(Food_ID,Food_Name,Description) values("abruzzese","abruzzese","菜一个意大利描述符(从面到小牛肉)热辣椒的自由使用,在意大利阿布鲁佐地区的风格。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("absinthe","苦艾酒","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("açai","黑莓","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acai berry","莓","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Ac'cent","Ac 'cent","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acerola","针叶","一个小小的树和小礼盒,cherrylike水果生长,发现主要在西印度群岛。水果,甜的味道和维生素C浓度最高的国家之一,用于甜点和保存。也称为巴巴多斯樱桃,波多黎各的樱桃和西印度樱桃。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Acesulfame-K","Acesulfame-K","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acetic acid","醋酸","醋酸形成时常见的空气中的细菌与酒精的发酵交互的解决方案如葡萄酒、啤酒和苹果酒。醋酸是使醋酸成分。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aceto","aceto","意大利的''醋''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("achar","亚","一个东印度的词指腌咸津津乐道。它们可以甜或热,这取决于佐料补充道。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("achiote seed","胭脂树的种子","稍musky-flavored红木树的种子可以全部或在东印度,西班牙和拉丁美洲的市场。购买整个种子时一个生锈的红色,棕色的种子是老的无味。胭脂树的种子也被称为红木,粘贴和粉末形式,在美国用于颜色黄油、人造黄油、奶酪和熏鱼。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acid","酸","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acid orange","酸橙","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acidophilous milk","酸奶","看到牛奶");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acidulated water","酸化水","水,少量的醋、柠檬或酸橙汁已被添加。作为浸泡,以防止变色的一些水果和蔬菜(比如苹果和洋蓟)迅速变暗时减少表面暴露在空气中。它也可以用作烹饪中。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acini di pepe","腺泡迪佩佩","意大利''花椒。''小米粒状的面食。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acitrón acitrónes","acitron acitrones","pl.看到nopales");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ackee","西非荔枝果","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acorn","橡子","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acorn squash","小青南瓜","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("acqua","水","意大利对水。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("additives","添加剂、食品","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ade","外壳","饮料,比如柠檬水或酸橙汽水,由结合水、糖和柑橘类果汁。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("adjust, to","调整,","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("adobado","adobado","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("adobo","阿斗波","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("adobo sauce","阿斗波酱","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("advocaat","荷兰产蛋酒","荷兰,brandy-based eggnog-flavored利口酒。全名是advocaatenborrel,荷兰''主(或律师)喝。''");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aemono","aemono","穿着日本术语,意思是''食物'',指saladlike菜加上酱的成分。敷料的组成各不相同,但通常是基于浓浆豆腐。Aemono菜肴通常是冷冻的开胃菜,虽然有时候日本食客吃年底前一餐饭。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aerate","让空气进入","一个术语用于烹饪作为一个筛选的同义词。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Affidelice","Affidelice","époisses须要");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affinage","精炼","法国术语的过程中完成(成熟)奶酪,一个完美的成熟。参见仿射。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affinatore","affinatore","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affiné","推敲","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affineur","affineur","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affogato","Affogato","一勺香草冰淇淋和冰淇淋,一杯热咖啡。虽然传统的香草,巧克力冰淇淋有时被使用,在这种情况下,甜点成为(''淹没'')。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affumicata","affumicata","意大利的''吸烟'',如熏肉或烟熏奶酪。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("affumicato","affumicato","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("African horned cucumber","非洲角黄瓜","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agar","琼脂","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agar-agar","琼脂","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agave","龙舌兰","也被称为世纪植物,这个家庭的肉质植物生长在美国西南部,墨西哥和中美洲。尽管有毒原料时,龙舌兰甜,温和的味道当烤或制成糖浆。某些品种用于生产酒精饮料麦斯卡尔酒,龙舌兰酒和龙舌兰酒。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("age","年龄","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aged","岁的","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aged meat","岁的肉","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agedashi","agedashi","日本的食物油炸豆腐萝卜,katsuobushi(干鲣鱼金枪鱼片),姜和酱油、味醂蘸酱。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agemono","Agemono","日本的术语,指炸(见油炸),这种烹饪方法制作的食品。天妇罗是日本最著名的食物煮熟以这种方式。炸在锅里被称为一个agemono-nabe ,这是类似中国的锅。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aging","老化","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aglio","aglio","意大利''大蒜。''");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aglio e olio","aglio和olio","意大利''大蒜和石油,''指的是酱大蒜和热橄榄油用于面食。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agneau","agneau","法国的''羔羊''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agnello","agnello","意大利的''羔羊''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agnolotti","肉饺","意大利''祭司的帽子。''小月牙形状的填充ravioli-style面食。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agresto","agresto","意大利''尖酸刻薄''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agrodolce","agrodolce","意大利的糖醋味(dolce意味着甜、农业是酸);法国的代名词。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agua","水","西班牙语和葡萄牙语,分别为''水''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("agua fresca","阿瓜fresca","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aguacate","aguacate","鳄梨的西班牙语单词。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aguardente","aguardente","葡萄牙的''白兰地'',更广泛的意义是为精神蒸馏从水果和蔬菜(见蒸馏)。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aguardiente","这","西班牙语为''燃烧水''(类似于北美的消防水),这是一个通用术语的几个强大的,低质量的精神。在西班牙,这一术语是指brandy-based饮用由马克。南美这德迦南是一个粗基于甘蔗酒,有时加入茴香种子。也看到巴西朗姆酒。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aguardiente de cana","甜酒的监狱","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ahi","你好","夏威夷名称黄鳍金枪鱼、大眼金枪鱼。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aigre-doux","aigre-doux","法国术语组合口味的酸(aigre)和甜(甜香槟)。aigre-doux酱可能同时包含醋和糖。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aïoli","蒜泥蛋黄酱","强味从法国南部普罗旺斯地区的大蒜蛋黄酱。这是一个受欢迎的伴奏鱼、肉和蔬菜。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Airelle","Airelle","一个cranberry-flavored白兰地酒。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Aisy Cendré","Aisy Cendre","< em须要 >上查阅过去各期époisses勃艮第");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ajijsuke-nori","ajijsuke-nori","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aji-no-moto","aji-no-moto","日本名字mono-sodium谷氨酸(味精)。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ajowan","ajowan","虽然相关的香菜和孜然,ajowan味道更像百里香涩边缘。这个土生土长的印度南部可以在印度市场在地面或种子的形式。紫红色的浅棕色的种子像芹菜种子大小和形状。Ajowan通常添加到chutneys,咖喱菜,面包和豆类。也称为使弹回。参见香料。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ajvar","ajvar","一个受欢迎的烹饪喜欢在南斯拉夫和希腊由烤甜红辣椒,茄子,大蒜、橄榄油、盐、胡椒,有时,辣椒。Ajvar可以作为开胃菜或配菜。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("ajwain","ajwain","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("akala","阿卡拉","来自夏威夷,这甜,多汁的浆果与一个非常大的树莓。它几乎可以范围的颜色从红色到紫色,也是很好的吃平原或堵塞和馅饼。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("aku","鲔","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("akule","akule","这个夏威夷鱼,也称为大眼鲷竹荚鱼,通常是盐和干。参见鱼。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("al","在","一个意大利单词,意为''在''、''''或''。''例如,咬起来硬的意思是''牙齿''。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("al dente","咬起来硬的","一个意大利词,意为''牙齿'',用来形容煮意大利面或其他食物,直到它提供了一个轻微的抵抗当咬到,但这不是软或过头了。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("al forno","''《","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("al fresco","在户外","意大利''新鲜''或''酷'',所指的态势在户外就餐,无论是在餐厅或野餐。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("al pastor","艾尔牧师","N/A");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Alaska cod","阿拉斯加鳕鱼","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Alaska king crab","阿拉斯加帝王蟹","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("albacore","长鳍","看到金枪鱼");
insert into Foods_CN(Food_ID,Food_Name,Description) values("Albert sauce","艾伯特酱","Usually served with beef, this is a rich horseradish sauce with a base of butter, flour and cream.");
insert into Foods_CN(Food_ID,Food_Name,Description) values("albóndiga","albondiga","西班牙单词''肉丸。''林林总总的名称是一个广受欢迎的墨西哥和西班牙菜辣的肉丸,通常在番茄酱。Sopade林林总总是beef-broth汤小丸子和切碎的蔬菜。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("albondigas","林林总总","");
insert into Foods_CN(Food_ID,Food_Name,Description) values("albumen","蛋白","蛋清的老式的词。");
insert into Foods_CN(Food_ID,Food_Name,Description) values("albumin","白蛋白","的蛋白质部分蛋白,包括整个的70%左右。白蛋白是动物血液中还发现,牛奶、植物和种子。");
