insert into Foods(Food_ID,Lang)values("à blanc","EN|CN");
insert into Foods(Food_ID,Lang)values("à la","EN|CN");
insert into Foods(Food_ID,Lang)values("à la carte","EN|CN");
insert into Foods(Food_ID,Lang)values("à la diable","EN|CN");
insert into Foods(Food_ID,Lang)values("à la king","EN|CN");
insert into Foods(Food_ID,Lang)values("à la mode","EN|CN");
insert into Foods(Food_ID,Lang)values("a labarigoule","EN|CN");
insert into Foods(Food_ID,Lang)values("à point","EN|CN");
insert into Foods(Food_ID,Lang)values("abalone","EN|CN");
insert into Foods(Food_ID,Lang)values("abbacchio","EN|CN");
insert into Foods(Food_ID,Lang)values("Abbaye de Belloc (Bellocq)","EN|CN");
insert into Foods(Food_ID,Lang)values("abby","EN|CN");
insert into Foods(Food_ID,Lang)values("aboyeur","EN|CN");
insert into Foods(Food_ID,Lang)values("abruzzese","EN|CN");
insert into Foods(Food_ID,Lang)values("absinthe","EN|CN");
insert into Foods(Food_ID,Lang)values("açai","EN|CN");
insert into Foods(Food_ID,Lang)values("acai berry","EN|CN");
insert into Foods(Food_ID,Lang)values("Ac'cent","EN|CN");
insert into Foods(Food_ID,Lang)values("acerola","EN|CN");
insert into Foods(Food_ID,Lang)values("Acesulfame-K","EN|CN");
insert into Foods(Food_ID,Lang)values("acetic acid","EN|CN");
insert into Foods(Food_ID,Lang)values("aceto","EN|CN");
insert into Foods(Food_ID,Lang)values("achar","EN|CN");
insert into Foods(Food_ID,Lang)values("achiote seed","EN|CN");
insert into Foods(Food_ID,Lang)values("acid","EN|CN");
insert into Foods(Food_ID,Lang)values("acid orange","EN|CN");
insert into Foods(Food_ID,Lang)values("acidophilous milk","EN|CN");
insert into Foods(Food_ID,Lang)values("acidulated water","EN|CN");
insert into Foods(Food_ID,Lang)values("acini di pepe","EN|CN");
insert into Foods(Food_ID,Lang)values("acitrón acitrónes","EN|CN");
insert into Foods(Food_ID,Lang)values("ackee","EN|CN");
insert into Foods(Food_ID,Lang)values("acorn","EN|CN");
insert into Foods(Food_ID,Lang)values("acorn squash","EN|CN");
insert into Foods(Food_ID,Lang)values("acqua","EN|CN");
insert into Foods(Food_ID,Lang)values("additives","EN|CN");
insert into Foods(Food_ID,Lang)values("ade","EN|CN");
insert into Foods(Food_ID,Lang)values("adjust","EN|CN");
insert into Foods(Food_ID,Lang)values("adobado","EN|CN");
insert into Foods(Food_ID,Lang)values("adobo","EN|CN");
insert into Foods(Food_ID,Lang)values("adobo sauce","EN|CN");
insert into Foods(Food_ID,Lang)values("advocaat","EN|CN");
insert into Foods(Food_ID,Lang)values("aemono","EN|CN");
insert into Foods(Food_ID,Lang)values("aerate","EN|CN");
insert into Foods(Food_ID,Lang)values("Affidelice","EN|CN");
insert into Foods(Food_ID,Lang)values("affinage","EN|CN");
insert into Foods(Food_ID,Lang)values("affinatore","EN|CN");
insert into Foods(Food_ID,Lang)values("affiné","EN|CN");
insert into Foods(Food_ID,Lang)values("affineur","EN|CN");
insert into Foods(Food_ID,Lang)values("affogato","EN|CN");
insert into Foods(Food_ID,Lang)values("affumicata","EN|CN");
insert into Foods(Food_ID,Lang)values("affumicato","EN|CN");
insert into Foods(Food_ID,Lang)values("African horned cucumber","EN|CN");
insert into Foods(Food_ID,Lang)values("agar","EN|CN");
insert into Foods(Food_ID,Lang)values("agar-agar","EN|CN");
insert into Foods(Food_ID,Lang)values("agave","EN|CN");
insert into Foods(Food_ID,Lang)values("age","EN|CN");
insert into Foods(Food_ID,Lang)values("aged","EN|CN");
insert into Foods(Food_ID,Lang)values("aged meat","EN|CN");
insert into Foods(Food_ID,Lang)values("agedashi","EN|CN");
insert into Foods(Food_ID,Lang)values("agemono","EN|CN");
insert into Foods(Food_ID,Lang)values("aging","EN|CN");
insert into Foods(Food_ID,Lang)values("aglio","EN|CN");
insert into Foods(Food_ID,Lang)values("aglio e olio","EN|CN");
insert into Foods(Food_ID,Lang)values("agneau","EN|CN");
insert into Foods(Food_ID,Lang)values("agnello","EN|CN");
insert into Foods(Food_ID,Lang)values("agnolotti","EN|CN");
insert into Foods(Food_ID,Lang)values("agresto","EN|CN");
insert into Foods(Food_ID,Lang)values("agrodolce","EN|CN");
insert into Foods(Food_ID,Lang)values("agua","EN|CN");
insert into Foods(Food_ID,Lang)values("agua fresca","EN|CN");
insert into Foods(Food_ID,Lang)values("aguacate","EN|CN");
insert into Foods(Food_ID,Lang)values("aguardente","EN|CN");
insert into Foods(Food_ID,Lang)values("aguardiente","EN|CN");
insert into Foods(Food_ID,Lang)values("aguardiente de cana","EN|CN");
insert into Foods(Food_ID,Lang)values("ahi","EN|CN");
insert into Foods(Food_ID,Lang)values("aigre-doux","EN|CN");
insert into Foods(Food_ID,Lang)values("aïoli","EN|CN");
insert into Foods(Food_ID,Lang)values("Airelle","EN|CN");
insert into Foods(Food_ID,Lang)values("Aisy Cendré","EN|CN");
insert into Foods(Food_ID,Lang)values("ajijsuke-nori","EN|CN");
insert into Foods(Food_ID,Lang)values("aji-no-moto","EN|CN");
insert into Foods(Food_ID,Lang)values("ajowan","EN|CN");
insert into Foods(Food_ID,Lang)values("ajvar","EN|CN");
insert into Foods(Food_ID,Lang)values("ajwain","EN|CN");
insert into Foods(Food_ID,Lang)values("akala","EN|CN");
insert into Foods(Food_ID,Lang)values("aku","EN|CN");
insert into Foods(Food_ID,Lang)values("akule","EN|CN");
insert into Foods(Food_ID,Lang)values("al","EN|CN");
insert into Foods(Food_ID,Lang)values("al dente","EN|CN");
insert into Foods(Food_ID,Lang)values("al forno","EN|CN");
insert into Foods(Food_ID,Lang)values("al fresco","EN|CN");
insert into Foods(Food_ID,Lang)values("al pastor","EN|CN");
insert into Foods(Food_ID,Lang)values("Alaska cod","EN|CN");
insert into Foods(Food_ID,Lang)values("Alaska king crab","EN|CN");
insert into Foods(Food_ID,Lang)values("albacore","EN|CN");
insert into Foods(Food_ID,Lang)values("Albert sauce","EN|CN");
insert into Foods(Food_ID,Lang)values("albóndiga","EN|CN");
insert into Foods(Food_ID,Lang)values("albondigas","EN|CN");
insert into Foods(Food_ID,Lang)values("albumen","EN|CN");
insert into Foods(Food_ID,Lang)values("albumin","EN|CN");
